spring.application.name=cake-business
spring.datasource.url=jdbc:postgresql://127.0.0.1:5433/cake_business
spring.datasource.username=postgres
spring.datasource.password=Ibryasfah@032024P

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false